{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "saas-app.fullname" . }}
  labels:
    {{- include "saas-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      {{- toYaml .Values.rollout.strategy.canary | nindent 6 }}
      canaryService: {{ include "saas-app.fullname" . }}-canary
      stableService: {{ include "saas-app.fullname" . }}
      trafficRouting:
        nginx:
          stableIngress: {{ include "saas-app.fullname" . }}
          annotationPrefix: nginx.ingress.kubernetes.io
          additionalIngressAnnotations:
            canary-by-header: X-Canary
  selector:
    matchLabels:
      {{- include "saas-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "saas-app.selectorLabels" . | nindent 8 }}
        tenant-id: {{ .Values.tenant.id | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: TENANT_ID
          value: {{ .Values.tenant.id | quote }}
        - name: TENANT_NAME
          value: {{ .Values.tenant.name | quote }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "saas-app.fullname" . }}-db
              key: database-url
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
{{- end }}
