apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant2-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: saas-platform
  source:
    repoURL: https://github.com/your-org/saas-platform
    targetRevision: HEAD
    path: helm-charts/saas-app
    helm:
      valueFiles:
      - values.yaml
      - values-tenant2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5
