# Platform namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: saas-platform
  labels:
    name: saas-platform
    type: shared
---
# Tenant namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: tenant1
  labels:
    name: tenant1
    type: tenant
    tenant-id: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant2
  labels:
    name: tenant2
    type: tenant
    tenant-id: "2"
---
# Network policies for tenant isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tenant1-isolation
  namespace: tenant1
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: saas-platform
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tenant2-isolation
  namespace: tenant2
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: saas-platform
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
