apiVersion: v2
name: saas-app
description: Multi-tenant SaaS application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: 15.5.38
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
